version: "1"
image: runicos/base
pipeline:
  audio:
    capability: SOUND
    outputs:
      - type: I16
        dimensions:
          - 2
    args:
      hz: 16000
      sample-duration-ms: 960
  model:
    model: "./yamnet.tflite"
    inputs:
      - audio
    outputs:
      - type: F32
        dimensions:
          - 521
          - 1024
          - 64
  serial:
    out: serial
    inputs:
      - model
