version: 1
image: runicos/base

pipeline:
  image:
    capability: IMAGE
    outputs:
      - type: u8
        dimensions: [1,320,320,3]
    args:
      pixel-format: "@PixelFormat::RGB"
      height: 320
      width: 320
  normalized_image:
    proc-block: "hotg-ai/proc-blocks#image-normalization"
    inputs:
      - image
    outputs:
      - type: f32
        dimensions: [1, 320, 320, 3]
  east_text_detector:
    model: "./east-text-detector_fp16_1.tflite"
    inputs:
      - normalized_image
    outputs:
      outputs:
      - type: f32
        dimensions: [1,80,80,1]
      - type: f32
        dimensions: [1,80,80,5]
  serial:
    out: SERIAL
    inputs:
      - east_text_detector