version: 1
image: runicos/base

pipeline:
  image:
    capability: IMAGE
    outputs:
      - type: u8
        dimensions: [1,513,513,3]
    args:
      height: 513
      width: 513
      pixel-format: "@PixelFormat::RGB"
  normalize:
    proc-block: "hotg-ai/proc-blocks#image-normalization"
    inputs:
     - image
    outputs:
      - type: f32
        dimensions: [1, 513, 513, 3]
  deep_lab:
    model: "./mobilenetv2-dm05-coco_int8_1.tflite"
    inputs:
      - normalize
    outputs:
      - type: f32
        dimensions: [1,513,513,21]
  segmentation_map:
    proc-block: "hotg-ai/proc-blocks#segment_output"
    inputs:
      - deep_lab
    outputs:
      - type: u32
        dimensions: [513, 513]
      - type: u32
        dimensions: [20]
  label:
    proc-block: "hotg-ai/proc-blocks#label"
    inputs:
      - segmentation_map.1
    outputs:
      - type: Utf8
        dimensions: [20]
    args:
      labels:
        - background
        - aeroplane
        - bicycle
        - bird
        - boat
        - bottle
        - bus
        - car
        - cat
        - chair
        - cow
        - diningtable
        - dog
        - horse
        - motorbike
        - person
        - pottedplant
        - sheep
        - sofa
        - train
        - tv
  serial:
    out: SERIAL
    inputs:
      - label
      - segmentation_map.0