version: 1
image: runicos/base

pipeline:
  image:
    capability: RAND
    outputs:
      - type: f32
        dimensions: [2, 2]
    # args:
    #   pixel-format: "@PixelFormat::RGB"
    #   height: 224
    #   width: 224
  normalize:
    proc-block: "hotg-ai/proc-blocks@v0.11.3#normalize"
    inputs:
      - image
    outputs:
      - type: f32
        dimensions: [1, ]
  serial:
    out: SERIAL
    inputs:
      - image
      - normalize
