version: 1
image: runicos/base

pipeline:
  image:
    capability: IMAGE
    outputs:
      - type: u8
        dimensions: [1, 257, 257, 3]
    args:
      height: 257
      width: 257
      pixel-format: "@PixelFormat::RGB"
  normalize:
    proc-block: "hotg-ai/proc-blocks@v0.11.2#image-normalization"
    inputs:
      - image
    outputs:
      - type: f32
        dimensions: [1, 257, 257, 3]
  deep_lab:
    model: "./deeplabv3.tflite"
    inputs:
      - normalize
    outputs:
      - type: f32
        dimensions: [1, 257, 257, 21]
  segmentation_map:
    proc-block: "hotg-ai/proc-blocks@v0.11.2#segment_output"
    inputs:
      - deep_lab
    outputs:
      - type: u32
        dimensions: [257, 257]
      - type: u32
        dimensions: [20]
  label:
    proc-block: "hotg-ai/proc-blocks@v0.11.2#label"
    inputs:
      - segmentation_map.1
    outputs:
      - type: Utf8
        dimensions: [20]
    args:
      wordlist: |
        - background
        - aeroplane
        - bicycle
        - bird
        - boat
        - bottle
        - bus
        - car
        - cat
        - chair
        - cow
        - diningtable
        - dog
        - horse
        - motorbike
        - person
        - pottedplant
        - sheep
        - sofa
        - train
        - tv
  serial:
    out: SERIAL
    inputs:
      - label
      - segmentation_map.0
