version: 1
image: runicos/base

pipeline:
  image:
    capability: IMAGE
    outputs:
      - type: u8
        dimensions: [1,257,257,3]
    args:
      height: 257
      width: 257
      pixel-format: "@PixelFormat::RGB"
  normalize:
    proc-block: "hotg-ai/proc-blocks#image-normalization"
    inputs:
     - image
    outputs:
      - type: f32
        dimensions: [1, 257, 257, 3]
  deep_lab:
    model: "./deeplabv3.tflite"
    inputs:
      - normalize
    outputs:
      - type: f32
        dimensions: [1,257,257,21]
  serial:
    out: SERIAL
    inputs:
      - deep_lab