version: 1
image: runicos/base

pipeline:
  image:
    capability: IMAGE
    outputs:
      - type: u8
        dimensions: [1,192,192,3]
    args:
      height: 192
      width: 192
      pixel-format: "@PixelFormat::RGB"
  object_localizer:
    model: "./object_localizer_v1_1_default_1.tflite"
    inputs:
      - image
    outputs:
      - type: f32
        dimensions: [1,100, 4]
      - type: f32
        dimensions: [1,100]
      - type: f32
        dimensions: [1,100]
      - type: f32
        dimensions: [1]
  serial:
    out: SERIAL
    inputs:
      - object_localizer.0
      - object_localizer.1
      - object_localizer.2
      - object_localizer.3