version: 1
image: runicos/base

pipeline:
  image:
    capability: IMAGE
    outputs:
      - type: u8
        dimensions: [1, 96, 96, 3]
    args:
      height: 96
      width: 96
      pixel-format: "@PixelFormat::RGB"
  # normalize:
  #   proc-block: "hotg-ai/proc-blocks@v0.11.2#image-normalization"
  #   inputs:
  #     - image
  #   outputs:
  #     - type: f32
  #       dimensions: [1, 96, 96, 3]
  model:
    model: "./mask-detection.tflite"
    inputs:
      - image
    outputs:
      - type: f32
        dimensions: [1, 3]
  most_confident_index:
    proc-block: "hotg-ai/proc-blocks@v0.11.2#most_confident_indices"
    inputs:
      - model
    outputs:
      - type: u32
        dimensions: [1]
    args:
      count: 1
  label:
    proc-block: "hotg-ai/proc-blocks@v0.11.2#label"
    inputs:
      - most_confident_index
    outputs:
      - type: utf8
        dimensions: [1]
    args:
      wordlist: |
        unknown
        mask
        no_mask
  serial:
    out: SERIAL
    inputs:
      - label
