version: 1
image: runicos/base

pipeline:
  image:
    capability: IMAGE
    outputs:
      - type: u8
        dimensions: [1,512,512,3]
    args:
      height: 512
      width: 512
      pixel-format: "@PixelFormat::RGB"
  normalize:
    proc-block: "hotg-ai/proc-blocks#image-normalization"
    inputs:
    - image
    outputs:
    - type: f32
      dimensions: [1, 512, 512, 3]
  cartoongan:
    model: "./cartoongan_dr_1.tflite"
    inputs:
      - normalize
    outputs:
      - type: f32
        dimensions: [1,512,512,3]
  serial:
    out: SERIAL
    inputs:
      - cartoongan