[package]
name = "audio_float_conversion"
version = "0.6.1-dev"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
pretty_assertions = "0.7.2"

[dependencies]
hotg-rune-proc-blocks = "0.9.3"
